name: 'Check script formatting'

on:
  push:
    paths:
      - '.github/workflows/check-script-formatting.yml'
      - '**.sh'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/check-script-formatting.yml'
      - '**.sh'
      - '.editorconfig'
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  shfmt:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'

      - name: 'Check shell script formatting'
        # https://github.com/mvdan/sh
        run: docker run --volume "$GITHUB_WORKSPACE":/mnt --workdir /mnt mvdan/shfmt:latest -w .

      - name: 'Formatting diff'
        run: git diff --color --exit-code
