name: 'shellcheck'

on:
  push:
    paths:
      - '.github/workflows/check-script-formatting.yml'
      - '**.sh'
  pull_request:
    paths:
      - '.github/workflows/check-script-formatting.yml'
      - '**.sh'
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  shellcheck:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'

      - name: 'Run shellCheck'
        uses: 'azohra/shell-linter@latest'
